# Generated by Django 4.1.8 on 2023-05-03 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title_ru",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Наименование товара ru"),
                ),
                ("title_uz", models.CharField(blank=True, max_length=255, null=True, verbose_name="Tovar nomi uz")),
                ("title_en", models.CharField(blank=True, max_length=255, null=True, verbose_name="Product name en")),
                ("code", models.CharField(blank=True, max_length=50, null=True, verbose_name="Код товара")),
                (
                    "unit",
                    models.CharField(
                        choices=[("м2", "м2"), ("шт", "шт")],
                        default="шт",
                        max_length=10,
                        verbose_name="Единица измерения",
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=20, null=True, verbose_name="Торговая марка")),
                ("proportions", models.CharField(max_length=10, verbose_name="Размеры")),
                ("description_ru", models.TextField(blank=True, null=True, verbose_name="Описание ru")),
                ("description_uz", models.TextField(blank=True, null=True, verbose_name="Tavsif uz")),
                ("description_en", models.TextField(blank=True, null=True, verbose_name="Description en")),
                ("manufacturer", models.CharField(blank=True, max_length=20, null=True, verbose_name="Производитель")),
                ("rest_count", models.FloatField(default=0, verbose_name="Остаток товара")),
                ("is_float", models.BooleanField(default=False, verbose_name="Остаток является нецелым")),
                ("price", models.IntegerField(default=0, verbose_name="Цена")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="Удален ли товар")),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name_ru", models.CharField(max_length=100, verbose_name="Название категории ru")),
                (
                    "name_uz",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="Kategoriya nomi uz"),
                ),
                (
                    "name_en",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="Product category en"),
                ),
            ],
            options={
                "verbose_name": "Бренд",
                "verbose_name_plural": "Бренды",
            },
        ),
        migrations.CreateModel(
            name="ProductUpdateLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("updated_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductShots",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="", verbose_name="Изображение")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="main.product")),
            ],
            options={
                "verbose_name": "Изображение товара",
                "verbose_name_plural": "Изображения товаров",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="main.productcategory"
            ),
        ),
    ]
